--SERVER1 system
--ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
alter session set container = ORCLPDB;
CREATE USER BDD_GLOBAL
    IDENTIFIED BY distribuit
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON system;
GRANT CREATE SESSION TO BDD_GLOBAL;
GRANT ALL PRIVILEGES TO BDD_GLOBAL;

CREATE USER BDD_CENTRALIZAT
    IDENTIFIED BY distribuit
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON system;
GRANT CREATE SESSION TO BDD_CENTRALIZAT;
GRANT ALL PRIVILEGES TO BDD_CENTRALIZAT;

CREATE USER BDD
    IDENTIFIED BY distribuit
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON system;
GRANT CREATE SESSION TO BDD;
GRANT ALL PRIVILEGES TO BDD;


    