--SERVER2 system
--ALTER PLUGGABLE DATABASE PDB2 OPEN;
alter session set container = PDB2;
CREATE USER BDD
    IDENTIFIED BY distribuit
    DEFAULT TABLESPACE USERS
    QUOTA UNLIMITED ON USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON system;
GRANT CREATE SESSION TO BDD;
GRANT ALL PRIVILEGES TO BDD;